export const productsSeeds = [
  {
    id: 23,
    nombre: "Harina Pan",
    costoDolar: 13,
    precio: 12,
    estado: 1,
    ganancia: 0.7,
    almacen: "sin asignar",
  },
  {
    id: 23,
    nombre: "TOALLA SANITARIAS ALWAYS NOCTURNAS  MORADAS DETALLADAS",
    costoDolar: 13,
    precio: 12,
    estado: 1,
    ganancia: 0.7,
    almacen: "sin asignar",
  },
  {
    id: 24,
    nombre: "Empanadas",
    costoDolar: 1,
    precio: 17,
    estado: 0,
    ganancia: 0.7,
    almacen: "sin asignar",
  },
  {
    id: 13,
    nombre: "Chile",
    costoDolar: 1,
    precio: 14,
    estado: 0,
    ganancia: 0.7,
    almacen: "sin asignar",
  },
];
